### ISSUE TITLE
Rename to "Papagayo-NG"

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/papagayo-ng#15]
Our version of Papagayo gets pretty different from the one provided by Lost Marble (https://github.com/LostMoho/Papagayo).
Would be nice to let our users to distinguish the versions to avoid confusions. For that purpose we can rename to "Papagayo-NG" ("NG" stands for "next generation"). ^__^

Some work needs to be done on that matter, i.e. replace "Papagayo" to "Papagayo-NG" everywhere in the code, add mention about original version of Lost Marble in About dialog, etc.

Anyone? ^__^

**Comment by steveway** [comment]
Sounds good by me. Papagayo-NG is a bit of a mouthful but I can't think of anything really better.
I was hesitant to make some bigger changes before, like adding the tagging system, but with this it should fit better.

**Comment by MaskedRetriever** [comment]
I was also thinking of adding some stuff for music... yeah, it might be a good idea.

**Comment by andeon** [comment]
I'd like to see another name of "talking bird", but I'm not sure if have good names, maybe **Galah**, **Magpie**.  Is Papagayo a Spanish word?

And I'm thinking also about: If keep the same name wouldn't have problems in the future case they return to the development.

**Comment by MaskedRetriever** [comment]
I think it's Portuguese, also I notice we're on Python and they're on C, so maybe Magpie would be a good choice because it has the syllable "Py" in it...

**Comment by steveway** [comment]
Mhh, I like the idea with Magpie or rather Magpy, but there is already a rather well known lip-sync software called Magpie, so we shouldn't use that:
http://www.thirdwishsoftware.com/magpiepro.html

**Comment by andeon** [comment]
@steveway I agree, bad idea with a commercial software already using the name. Looking at date I think that magpie inspired Papagayo name.

Another suggestion: **Hill Myna**, **Starling**, **Lyrebird** that's incredible, but it's not a pet https://www.youtube.com/watch?v=_2UcKFtwS5o

*_I had no idea there were many birds that could talking._

I tried too check about "ventriloquy" because lipsyc made me remember this, but [ventrilo](http://www.ventrilo.com/) word is already taken.

**Comment by morevnaproject** [comment]
Dear friends! I would like to keep "Papagayo" word in the name for the following reason: there are already many tutorials on YouTube about usage of Papagayo ([example](http://www.youtube.com/watch?v=-Y0Ox0cnlL4)). So, the people will be searching for something with "papagayo" word. Changing the name will leave them without a clue.

> If keep the same name wouldn't have problems in the future case they return to the development.

I am pretty sure we will not have problems. The original developer already returned to development once (when they released Papagayo 2.0). And we have our fork around for a long time already.

At the moment I am pretty much busy with production. My main question - who can take care about renaming to "Papagayo-NG"?

**Comment by steveway** [comment]
Makes sense, I would say we name it Papagayo-NG for now and maybe change it to something new somewhere down the line in the future.
Well, renaming it shouldn't be too difficult but how do we wan't to approach this github wise?
I'm still getting warm with git and would need some help/guideance/ideas with how we do this.

**Comment by morevnaproject** [comment]
I have renamed repository to "papagayo-ng" using Settings button of GitHub interface. Now it remains to change any mention of "Papagayo" to "Papagayo-NG" in the source.

**Comment by steveway** [comment]
Most things should be renamed now:
https://github.com/morevnaproject/papagayo-ng/pull/16

**Comment by morevnaproject** [comment]
Merged now. Thank you!
