### ISSUE TITLE
Feature request - volume control

### ISSUE THREAD

**Issue by tjoen** [morevnaproject/papagayo-ng#20]
It might be in the program somewhere, but I can't seem to adjust the volume of the wav?
##

**Comment by morevnaproject** [comment]
There is no volume control available within Papagayo-NG yet.

**Comment by steveway** [comment]
I've got a very stupid implementation working in my testing branch:
https://github.com/steveway/papagayo-ng/commit/f562dc0628277a2c16dc9d368477c52faac3eaa4
There is no GUI to change the volume, you need to change the self.volume value from 0 to 100.
I will most likely discard this idea.
The better solution would be to change the volume of the samples in SoundPlayer.py in the _play method directly.
I'm also using NamedTemporaryFile there, which is a better solution than the current fake temp file we use.

**Comment by steveway** [comment]
Alright, I created a quite well working version to a branch of mine here:
https://github.com/steveway/papagayo-ng/tree/working_vol
There is still no GUI to change the volume.
I'll do a few tests of this and when my other Pull request is done I'll create a Pull request for this before tackling the GUI part of this.

**Comment by steveway** [comment]
Pull-Request #24 should now fix this.

**Comment by tjoen** [comment]
Newest release has this feature, So closing it.
