### ISSUE TITLE
Appimage seems to be missing from Gumroad download.

### ISSUE THREAD

**Issue by mikobuntu** [morevnaproject/papagayo-ng#28]
Hi , The gumroad library only seems to contain the windows binary ( which automatically downloads when I click on " view product" )

**Comment by morevnaproject** [comment]
Please make sure to choose "Linux" from the dropdown list:

![112-1-3d-ref-screen-4](https://user-images.githubusercontent.com/332868/27209983-7ae4f744-5279-11e7-8e06-e842d9145a2a.png)

**Comment by mikobuntu** [comment]
Ah somehow I missed that option. Thanks. I have already downloaded the source anyway :)
