### ISSUE TITLE
Install latest from source on MacOS

### ISSUE THREAD

**Issue by taji** [morevnaproject/papagayo-ng#52]
Attempting to do the install from source on MacOS,  Coming back to python after a long absense. 
 Here's what I've done so far from a terminal:
- run _xcode-select --install_
- run _brew install openssl_
- run _export CFLAGS="-I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"_
- run  _export LDFLAGS="-L$(brew --prefix openssl)/lib"_
- run _brew install pyenv_
- run _brew install pyenv-virtualenv_
- run _pyenv install 3.6.8_
- run _pyenv virtualenv 3.6.8 papa_
- run _pyenv activate papa_
- run git clone https://github.com/morevnaproject/papagayo-ng.git
Inside the virtualenv:
    - run _pip install PySide2 numpy sounddevice wxpython_
    - cd into papagayo-ng folder.
    - run  _python3 papagayo-ng.py_

**_Error: papagayo-ng.py:19: UserWarning: You either don't have wx installed or you are using wxphoenix. Please test this with wx Version 2.8 before reporting errors!
  warnings.warn("You either don't have wx installed or you are using wxphoenix. Please test this with wx Version 2.8 before reporting errors!")_**

The readme doesn't indicated anything about wx, wxpython or wxpheonix.  I went ahead and pip installed wxpython, but the error message didnt change.  Any ideas?

UPDATE:  in a python repl, importing wx and then running wx.version() returns _'4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5'_

**Comment by morevnaproject** [comment]
@taji Thank you for reporting! Should be fixed now. Please to download latest sources and try again. ^__^

**Comment by taji** [comment]
Pulled down latest, reran and I'm seeing papagayo launching.   Ran into another issue, I'll open a new one.  Thanks! :-)

**Comment by taji** [comment]
Sorry to bother, but the changeset committed two days ago (see above) seems to have disappeared from master:

[01b86f3](https://github.com/morevnaproject/papagayo-ng/commit/01b86f34c898d6a88c80fc945fa169fa57db0f2b)

I'm looking at the project page and it shows the last commit for master was 9 days ago:

![image](https://user-images.githubusercontent.com/702031/52385969-82fb5780-2a49-11e9-981e-21c413147aaf.png)

Strange.  Did someone roll back?

**Comment by morevnaproject** [comment]
Probably someone did "git push --force"? ^__^ @steveway @evgenijkatunov @blackwarthog, any ideas?

BTW, I've just restored missing commits. ^__^

**Comment by steveway** [comment]
That was very likely me sorry. Wanted to set my master to be the same as this and must have mixed this up.
I'm a bit rusty with git.
Thanks for fixing.

**Comment by morevnaproject** [comment]
@steveway No problem! ^__^
