### ISSUE TITLE
ZeroDivisionError when breakdown the phonemes

### ISSUE THREAD

**Issue by chashikajw** [morevnaproject/papagayo-ng#63]
After execute the code and audio clip is imported, then when click the breakdown button to break down the phonemens, it show ZeroDivisionError
![pap](https://user-images.githubusercontent.com/21282060/65818593-80e04600-e230-11e9-90e7-d4a077238b44.png)

**Comment by steveway** [comment]
Was able to reproduce this.
It should be fixed with this commit:
https://github.com/steveway/papagayo-ng/commit/e3146316cdfa92f3510fb302a94d258dc0022a28
